#' Generate QUASAR pseudobulk mixtures and optional signature matrices
#'
#' Simulates pseudobulk RNA-seq expression profiles from single-cell count data
#' for QUASAR. Pseudobulk samples are generated by drawing cell-type proportions
#' from a Dirichlet distribution and sampling cells with replacement from the
#' corresponding cell-type pools. The function can also return bulk-specific
#' signature profiles for each cell type and a global signature matrix.
#'
#' Input can be provided as a single \code{Seurat} object, a single
#' \code{SingleCellExperiment} object, or as a count matrix together with a
#' matching metadata table.
#'
#' @param ... Input data. Supported formats are:
#' \itemize{
#'   \item a single \code{Seurat} object containing RNA counts and metadata,
#'   \item a single \code{SingleCellExperiment} object containing counts and
#'   column metadata,
#'   \item or two objects: a gene-by-cell count matrix and a metadata
#'   \code{data.frame} with cells in rows.
#' }
#' @param n_bulk_samples Integer. Number of pseudobulk samples to generate.
#' @param cells_per_bulk Integer. Number of cells to sample per
#'   pseudobulk sample.
#' @param cell_type_column Character. Name of the metadata column containing
#'   cell-type annotations.
#' @param patient_id_column Optional character. Name of the metadata column
#'   containing patient IDs. If provided, one patient is sampled per pseudobulk
#'   and cells are preferentially drawn from that patient.
#' @param select_ct Optional character vector. Cell types to retain. If
#'   \code{NULL}, all cell types are used.
#' @param dirich_alpha Numeric. Dirichlet concentration parameter used to sample
#'   cell-type fractions. Smaller values lead to more uneven mixtures.
#' @param seet Integer. Random seed for reproducible sampling.
#' @param sparse Logical. If \code{TRUE}, randomly sets a proportion of sampled
#'   cell-type fractions to zero before renormalization.
#' @param sparse_prob Numeric between 0 and 1. Probability of setting a
#'   cell-type fraction to zero when \code{sparse = TRUE}.
#' @param rare Logical. If \code{TRUE}, randomly replaces some cell-type
#'   fractions with small values to mimic rare populations.
#' @param rare_percentage Numeric between 0 and 1. Proportion of entries in the
#'   fraction matrix affected when \code{rare = TRUE}.
#' @param return_used_samples Logical. If \code{TRUE}, returns the sampled cell
#'   indices used for each pseudobulk sample and cell type.
#' @param return_patient_metadata Logical. If \code{TRUE} and
#'   \code{patient_id_column} is provided, returns the sampled patient ID for
#'   each pseudobulk sample.
#' @param return_signature_matrix Logical. If \code{TRUE}, computes and returns
#'   both bulk-specific signature profiles and a global signature matrix.
#' @param verbose Logical. If \code{TRUE}, prints a short runtime summary.
#'
#' @details
#' For each pseudobulk sample, cell-type fractions are drawn from a Dirichlet
#' distribution and converted into integer cell counts using
#' \code{cells_per_bulk}. Cells are then sampled with replacement and summed to
#' create bulk expression profiles.
#'
#' In patient-aware mode, one patient is sampled for each pseudobulk sample.
#' Cells are preferentially drawn from that patient's cells within each cell
#' type. If a patient-specific pool is empty for a given cell type, the full
#' cell-type pool is used as fallback.
#'
#' If \code{return_signature_matrix = TRUE}, the function additionally computes:
#' \itemize{
#'   \item \code{bulk_signature_profiles}: a list of gene-by-bulk matrices, one
#'   per cell type, containing bulk-specific mean expression profiles based on
#'   the realized sampled cells;
#'   \item \code{global_signature_matrix}: a gene-by-cell-type matrix obtained
#'   by averaging the bulk-specific signature profiles across all pseudobulk
#'   samples.
#' }
#'
#' The returned ground-truth proportions are based on the realized sampled cell
#' counts per cell type and bulk sample.
#'
#' @return A list with at least the following components:
#' \describe{
#'   \item{bulk_expression_profiles}{Numeric matrix of pseudobulk expression
#'   profiles with genes in rows and pseudobulk samples in columns.}
#'   \item{ground_truth_proportions}{Numeric matrix of realized cell-type
#'   proportions with pseudobulk samples in rows and cell types in columns.}
#'   \item{timing}{Named list containing runtime information for pseudobulk
#'   generation, optional signature computation, and total execution time.}
#' }
#'
#' Depending on the selected options, the returned list may also contain:
#' \describe{
#'   \item{used_samples_by_ct}{List of sampled cell indices per pseudobulk sample
#'   and cell type.}
#'   \item{bulk_patient_metadata}{\code{data.frame} linking simulated bulk
#'   sample IDs to sampled patient IDs.}
#'   \item{bulk_signature_profiles}{List of gene-by-bulk signature matrices, one
#'   per cell type.}
#'   \item{global_signature_matrix}{Numeric gene-by-cell-type matrix containing
#'   the global signature profiles.}
#' }
#'
#' @examples
#' 
#' \dontrun{
#' set.seed(1)
#' counts <- matrix(rpois(2000, lambda = 5), nrow = 100, ncol = 20)
#' rownames(counts) <- paste0("gene_", seq_len(nrow(counts)))
#' colnames(counts) <- paste0("cell_", seq_len(ncol(counts)))
#'
#' meta <- data.frame(
#'   cell_type = rep(c("T", "B"), each = 10),
#'   patient_id = rep(c("P1", "P2"), times = 10),
#'   row.names = colnames(counts)
#' )
#'
#' res <- quasar_sim_bulk(
#'   counts, meta,
#'   n_bulk_samples = 5,
#'   cells_per_bulk = 50,
#'   cell_type_column = "cell_type",
#'   patient_id_column = "patient_id",
#'   return_signature_matrix = TRUE
#' )
#'
#' dim(res$bulk_expression_profiles)
#' dim(res$ground_truth_proportions)
#' dim(res$global_signature_matrix)
#' 
#' }
#' 
#'
#' @importFrom SingleCellExperiment counts
#' @importFrom SummarizedExperiment colData
#' @importFrom MCMCpack rdirichlet
#' @importFrom Matrix sparseMatrix Diagonal Matrix rowMeans
#' @importFrom stats runif
#' @export
quasar_sim_bulk <- function(...,
                            n_bulk_samples,
                            cells_per_bulk,
                            cell_type_column = "cell_type",
                            patient_id_column = NULL,
                            select_ct = NULL,
                            dirich_alpha = 1,
                            seet = 1,
                            sparse = FALSE,
                            sparse_prob = 0.5,
                            rare = FALSE,
                            rare_percentage = 0.4,
                            return_used_samples = FALSE,
                            return_patient_metadata = FALSE,
                            return_signature_matrix = FALSE,
                            verbose = FALSE) {

  start_time_all <- Sys.time()
  args <- list(...)

  # --------------------------------------------------
  # Load count matrix & metadata
  # --------------------------------------------------
  if (length(args) == 1) {
    obj <- args[[1]]
    if (inherits(obj, "Seurat")) {
      count_matrix <- obj[["RNA"]]$counts
      cell_metadata <- obj@meta.data
    } else if (inherits(obj, "SingleCellExperiment")) {
      count_matrix <- SingleCellExperiment::counts(obj)
      cell_metadata <- as.data.frame(SummarizedExperiment::colData(obj))
    } else {
      stop("Single input must be Seurat or SingleCellExperiment object")
    }
  } else if (length(args) == 2) {
    count_matrix <- args[[1]]
    cell_metadata <- as.data.frame(args[[2]])
    common_cells <- intersect(colnames(count_matrix), rownames(cell_metadata))
    if (!length(common_cells))
      stop("No matching cells between counts and metadata")
    count_matrix <- count_matrix[, common_cells, drop = FALSE]
    cell_metadata <- cell_metadata[common_cells, , drop = FALSE]
  } else {
    stop("Invalid input format")
  }

  if (!cell_type_column %in% colnames(cell_metadata))
    stop("Missing cell type column in metadata")

  cell_types <- as.character(cell_metadata[[cell_type_column]])
  names(cell_types) <- colnames(count_matrix)

  # --------------------------------------------------
  # Restrict cell types
  # --------------------------------------------------
  if (!is.null(select_ct)) {
    keep_idx <- which(cell_types %in% select_ct)
    if (!length(keep_idx))
      stop("No cells found for given select_ct")
    count_matrix <- count_matrix[, keep_idx, drop = FALSE]
    cell_metadata <- cell_metadata[keep_idx, , drop = FALSE]
    cell_types <- cell_types[keep_idx]
    celltype_levels <- select_ct
  } else {
    celltype_levels <- unique(cell_types)
  }





  # --------------------------------------------------
  # Patient mode
  # --------------------------------------------------
  patient_mode <- !is.null(patient_id_column)
  if (patient_mode) {
    if (!patient_id_column %in% colnames(cell_metadata))
      stop("Missing patient ID column")
    patient_ids <- as.character(cell_metadata[[patient_id_column]])
    patient_levels <- unique(patient_ids)
  }

  set.seed(seet)

  # --------------------------------------------------
  # Precompute indices per cell type
  # --------------------------------------------------
  celltype_indices <- lapply(celltype_levels, function(ct) which(cell_types == ct))
  names(celltype_indices) <- celltype_levels

  # Patient pools (optional)
  if (patient_mode) {
    pools_by_pat <- lapply(celltype_levels, function(ct) {
      idx <- celltype_indices[[ct]]
      split(idx, patient_ids[idx])
    })
    names(pools_by_pat) <- celltype_levels
    chosen_patients <- sample(patient_levels, n_bulk_samples, replace = TRUE)
  }

  # --------------------------------------------------
  # Dirichlet fractions (CT x bulk)
  # --------------------------------------------------
  frac_matrix <- t(
    MCMCpack::rdirichlet(
      n_bulk_samples,
      rep(dirich_alpha, length(celltype_levels))
    )
  )

  # --------------------------------------------------
  # Sparsity / rare masking
  # --------------------------------------------------
  if (sparse) {
    drop_mask <- matrix(
      runif(length(frac_matrix)) < sparse_prob,
      nrow = nrow(frac_matrix)
    )
    frac_matrix[drop_mask] <- 0
  }

  if (rare) {
    rare_mask <- matrix(
      runif(length(frac_matrix)) < rare_percentage,
      nrow = nrow(frac_matrix)
    )
    frac_matrix[rare_mask] <- runif(sum(rare_mask), 0, 0.03)
  }




  # --------------------------------------------------
  # Renormalize columns
  # --------------------------------------------------
  col_sums <- colSums(frac_matrix)
  valid <- col_sums > 0
  frac_matrix[, valid] <-
    sweep(frac_matrix[, valid, drop = FALSE], 2, col_sums[valid], "/")

  # --------------------------------------------------
  # Allocate cells per CT per bulk
  # --------------------------------------------------
  counts_per_ct_all <- floor(frac_matrix * cells_per_bulk)


  empty_bulks <- which(colSums(counts_per_ct_all) == 0)
  if (length(empty_bulks)) {
    for (i in empty_bulks) {
      k <- sample(seq_len(nrow(counts_per_ct_all)), 1)
      counts_per_ct_all[k, i] <- 1
    }
  }

  # ==================================================
  # TIMING START: pseudobulk creation
  # ==================================================
  start_time_pseudobulk <- Sys.time()

  # --------------------------------------------------
  # FAST sampling with preallocation
  # --------------------------------------------------
  K <- length(celltype_levels)
  C <- ncol(count_matrix)
  N <- n_bulk_samples

  used_samples_by_ct <- vector("list", N)

  total_picks <- sum(counts_per_ct_all)
  ids_all <- integer(total_picks)
  grp_all <- integer(total_picks)
  pos_all <- 1L

  total_picks_ct <- rowSums(counts_per_ct_all)
  ids_ct <- lapply(total_picks_ct, function(n) integer(n))
  grp_ct <- lapply(total_picks_ct, function(n) integer(n))
  pos_ct <- rep.int(1L, K)

  for (i in seq_len(N)) {

    picks_ct_list <- vector("list", K)
    names(picks_ct_list) <- celltype_levels

    if (patient_mode) {
      pat_i <- chosen_patients[i]
    }

    for (k in seq_along(celltype_levels)) {
      ct <- celltype_levels[k]
      nct <- counts_per_ct_all[k, i]

      if (nct <= 0) {
        picks_ct_list[[k]] <- integer(0)
        next
      }

      # Select pool (patient-specific if available, else fallback to full CT pool)
      pool <- NULL
      if (patient_mode) {
        tmp <- pools_by_pat[[ct]][[pat_i]]
        if (!is.null(tmp) && length(tmp) > 0) pool <- tmp
      }
      if (is.null(pool) || length(pool) == 0) {
        pool <- celltype_indices[[ct]]
      }

      if (is.null(pool) || length(pool) == 0) {
        picks_ct_list[[k]] <- integer(0)
        next
      }

      picks <- sample(pool, nct, replace = TRUE)
      picks_ct_list[[k]] <- picks

      # Fill global selection
      rng_all <- pos_all:(pos_all + nct - 1L)
      ids_all[rng_all] <- picks
      grp_all[rng_all] <- i
      pos_all <- pos_all + nct

      # Fill per-CT selection
      p0 <- pos_ct[k]
      rng_ct <- p0:(p0 + nct - 1L)
      ids_ct[[k]][rng_ct] <- picks
      grp_ct[[k]][rng_ct] <- i
      pos_ct[k] <- p0 + nct
    }

    used_samples_by_ct[[i]] <- picks_ct_list
  }

  # --------------------------------------------------
  # Build bulk expression (genes x bulk) via sparse matmul
  # --------------------------------------------------
  S_all <- Matrix::sparseMatrix(
    i = ids_all,
    j = grp_all,
    x = 1,
    dims = c(C, N)
  )

  bulk_expression <- count_matrix %*% S_all
  bulk_expression <- as.matrix(bulk_expression)
  rownames(bulk_expression) <- rownames(count_matrix)
  colnames(bulk_expression) <- paste0("sample_", seq_len(N))

  # --------------------------------------------------
  # Ground truth proportions from realized allocations
  # --------------------------------------------------
  gt_props <- sweep(counts_per_ct_all, 2, colSums(counts_per_ct_all), "/")
  gt_props <- t(gt_props)
  colnames(gt_props) <- celltype_levels
  rownames(gt_props) <- paste0("sample_", seq_len(N))

  # ==================================================
  # TIMING END: pseudobulk creation
  # ==================================================
  end_time_pseudobulk <- Sys.time()
  time_pseudobulk_sec <- as.numeric(difftime(end_time_pseudobulk, start_time_pseudobulk, units = "secs"))

  result <- list(
    bulk_expression_profiles = bulk_expression,
    ground_truth_proportions = gt_props
  )

  if (return_used_samples) {
    result$used_samples_by_ct <- used_samples_by_ct
  }

  if (patient_mode && return_patient_metadata) {
    result$bulk_patient_metadata <- data.frame(
      sample_id = paste0("sample_", seq_len(N)),
      patient_id = chosen_patients
    )
  }

  # ==================================================
  # Signature matrix computation (separately timed)
  # ==================================================
  time_signature_sec <- NA_real_

  if (return_signature_matrix) {

    start_time_sig <- Sys.time()

    inv_n_list <- lapply(seq_len(K), function(k) {
      nct <- counts_per_ct_all[k, ]
      inv <- ifelse(nct > 0, 1 / nct, 0)
      Matrix::Diagonal(n = N, x = inv)
    })

    sig_list <- vector("list", K)
    names(sig_list) <- celltype_levels

    for (k in seq_len(K)) {
      if (total_picks_ct[k] == 0) {
        sig_list[[k]] <- Matrix::Matrix(0, nrow = nrow(count_matrix), ncol = N, sparse = TRUE)
        next
      }

      Wk <- Matrix::sparseMatrix(
        i = ids_ct[[k]],
        j = grp_ct[[k]],
        x = 1,
        dims = c(C, N)
      )

      Xk_sum  <- count_matrix %*% Wk         # genes x bulk (sum with multiplicity)
      Xk_mean <- Xk_sum %*% inv_n_list[[k]]  # genes x bulk (mean)
      sig_list[[k]] <- Xk_mean
    }

    # ---------------------------------------------
    # NEW: global signature (genes x celltypes)
    # ---------------------------------------------
    global_sig <- matrix(0, nrow = nrow(count_matrix), ncol = K,
                         dimnames = list(rownames(count_matrix), celltype_levels))

    for (k in seq_len(K)) {
      m <- sig_list[[k]]
      if (inherits(m, "dgCMatrix")) {
        global_sig[, k] <- Matrix::rowMeans(m)
      } else {
        global_sig[, k] <- rowMeans(as.matrix(m))
      }
    }

    result$bulk_signature_profiles <- sig_list
    result$global_signature_matrix <- global_sig

    end_time_sig <- Sys.time()
    time_signature_sec <- as.numeric(difftime(end_time_sig, start_time_sig, units = "secs"))
  }

  end_time_all <- Sys.time()
  time_total_sec <- as.numeric(difftime(end_time_all, start_time_all, units = "secs"))

  result$timing <- list(
    pseudobulk_seconds = time_pseudobulk_sec,
    signature_seconds  = time_signature_sec,
    total_seconds      = time_total_sec
  )

  if (verbose) {
    cat(sprintf(
      "Generated %d pseudobulks (%d cells each) from %d genes\n",
      N, cells_per_bulk, nrow(bulk_expression)
    ))
    cat(sprintf("Pseudobulk creation time: %.2f secs\n", time_pseudobulk_sec))

    if (return_signature_matrix) {
      cat(sprintf(
        "Computed bulk_signature_profiles (list of genesxbulk matrices per cell type)\nSignature matrix time: %.2f secs\n",
        time_signature_sec
      ))
      cat("Returned global_signature_matrix (genes x celltypes)\n")
    }

    cat(sprintf("Total quasar_sim_bulk time: %.2f secs\n", time_total_sec))
  }

  result
}